### ISSUE TITLE
OpenShift logging is disabled in production

### ISSUE THREAD

**Issue by luciddreamz** [sclorg/rails-ex#101]
Logging to STDOUT is disabled in production configuration as of the 5.1 upgrade unless `RAILS_LOG_TO_STDOUT` environment variable is set. OpenShift no longer captures log output:

![screen shot 2017-11-14 at 12 27 26 pm](https://user-images.githubusercontent.com/928421/32794634-603b48e6-c937-11e7-8a8f-49239e803ba4.png)

**Comment by coreydaley** [comment]
If this is a new rails default to have that if statement, it seems to me that it would be better to update the templates to include that env var and set the default to true, rather than making this change, as we will have to remember to keep making this change in the future.

https://github.com/openshift/rails-ex/tree/master/openshift/templates

**Comment by luciddreamz** [comment]
Anyone deploying from an old template (without the env var set) is still using this example repo.

**Comment by coreydaley** [comment]
If they are deploying the sample code in this repo, it's just for demo/testing purposes, and if they are deploying an actual application that they wrote, it won't be fixed by either change.

**Comment by luciddreamz** [comment]
@bparees @coreydaley You don't think people use our Rails configuration/example as a starting point for their own applications? I have 2 production applications that started as forks of this repo.

**Comment by bparees** [comment]
@luciddreamz leave me out of this, i'm fine w/ the change :)

**Comment by coreydaley** [comment]
@luciddreamz Yes, people use this as a starting point, but removing the if statement here will not update their existing code right?  They are not going to rebase this repo into their applications repo periodically correct?

**Comment by luciddreamz** [comment]
@coreydaley 100% of places where the template is currently deployed, aka every OpenShift cluster that currently exists, are cases where the Rails template exists without the new environment variable set. Every one of those templates points at this GitHub repo.

**Comment by coreydaley** [comment]
@luciddreamz The templates on a cluster are never updated to reflect recent updates?

**Comment by luciddreamz** [comment]
Correct, which is why the change you are proposing is a problem.

**Comment by bparees** [comment]
the templates are updated. but the deploymentconfigs that were created from an old version of the template are not going to be created from the new template, so they will not pick up the new env var.
