### ISSUE TITLE
templates are duplicated in container repository

### ISSUE THREAD

**Issue by pvalena** [sclorg/rails-ex#105]
```openshift/templates/*```
and
[s2i-ruby-container/examples](https://github.com/sclorg/s2i-ruby-container/tree/master/examples)

carry the same templates.

**Comment by bparees** [comment]
?

**Comment by pvalena** [comment]
Sorry, I somehow triggered send while writing title :)

**Comment by pvalena** [comment]
Which repo is to be 'upstream' one for `openshift/origin`?

**Comment by bparees** [comment]
the source of truth for application sample templates is the sample app repository (e.g. this one).

From there, they get pulled into openshift/origin, openshift/library, and openshift/openshift-ansible.

someday we want the path to be:

1) reside in app repo
2) pull into library
3) everything else (origin, openshift-ansible) pulls from library.

if by "container repository" you mean the image repository, I would not expect the templates to live there at all.  The templates are application specific, not image specific.

**Comment by pvalena** [comment]
Yes, that makes sense. In that case I'll remove the templates from s2i-ruby-container (that's the repository i meant).

FYI in some cases we have templates in container repository for the lack of example app (and there's no [intention](https://github.com/sclorg/mariadb-container/pull/57#commitcomment-26303905) to create one). 

Thanks for quick response!
