### ISSUE TITLE
PG::ConnectionBad with Openshift Deployment

### ISSUE THREAD

**Issue by jbltx** [sclorg/rails-ex#108]
I just tried to deploy a rails app in Openshift Online using this repo as reference for my Image, but the deployment has failed 

```bash
$ oc logs -f myapp-1-deploy
--> pre: Running hook pod ...
Executing bundle exec 'rake db:migrate' ...
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/opt/app-root/src/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/opt/app-root/src/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/opt/app-root/src/bundle/ruby/2.3.0/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql_adapter.rb:701:in `connect'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql_adapter.rb:220:in `initialize'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/connection_handling.rb:88:in `connection'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/schema_migration.rb:20:in `table_exists?'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/schema_migration.rb:24:in `create_table'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1125:in `initialize'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in `new'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:1007:in `up'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:985:in `migrate'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/opt/app-root/src/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/opt/app-root/src/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
--> pre: Failed
error: pre hook failed: the pre hook failed: , aborting rollout of mynamespace/myapp-1
```

It seems it can`t connect to the Postgresql database (which is well deployed and running).

So i don't think if the cluster is able to define these variables :

```yml
  host: <%= ENV["#{db_service}_SERVICE_HOST"] %>
  port: <%= ENV["#{db_service}_SERVICE_PORT"] %>
```

In the Openshift default **DeploymentConfig**, there's no host or port environment variables defined. Not sure if I need to explicitly define them during app creation since it's not written in [the documentation here](https://docs.openshift.com/enterprise/3.1/dev_guide/app_tutorials/ruby_on_rails.html#creating-the-frontend-service).

So what kind of changes do I need to make ? Thank you.

**Comment by bparees** [comment]
those variables would have been created by you deploying the DB service:

```
oc new-app postgresql -e POSTGRESQL_DATABASE=db_name -e POSTGRESQL_USER=username -e POSTGRESQL_PASSWORD=password
```

your issue is that i don't think DATABASE_SERVICE_NAME is defined:
https://github.com/openshift/rails-ex/blob/master/config/database.yml#L5

assuming you followed the other instructions (and therefore have a service named "postgresql" defined), it should be set to `POSTGRESQL`

we'll fix up the doc.

**Comment by bparees** [comment]
@coreydaley it looks like the rails tutorial has bit-rotted:
https://docs.openshift.org/latest/dev_guide/dev_tutorials/ruby_on_rails.html

at a minimum it doesn't instruct users to define a DATABASE_SERVICE_NAME variable which i think is necessary for the rails bits to get a proper DB configuration.  Can you walk through it and fix up the steps?

Thanks

**Comment by jbltx** [comment]
I think you're right, there's a problem with this variable, but it was already there in the DeploymentConfig file : 

```yml
spec:
  template:
    spec:
      containers:
        - env:
            - name: DATABASE_SERVICE_NAME
              value: postgresql-database
```
Indeed, the issue was the name of my postgresql app which has a dash in its name (`postgresql-database`). So in its database configuration file, Rails was trying to find invalid environment variables `POSTGRESQL-DATABASE_SERVICE_HOST` and `POSTGRESQL-DATABASE_SERVICE_PORT`. 

Using an appropriate name for an environnement variable as app name resolves the issue.

Thank you !

**Comment by bparees** [comment]
Did you deploy this using the template(https://github.com/openshift/rails-ex/blob/master/openshift/templates/rails-postgresql.json) or the documented instructions(https://docs.openshift.org/latest/dev_guide/dev_tutorials/ruby_on_rails.html)?

The template does indeed define DATABASE_SERVICE_NAME, but the instructions(which don't use the template) do not appear to do so, so i think we still need to clean up the instructions.

**Comment by coreydaley** [comment]
@bparees sure, pr incoming
