### ISSUE TITLE
List of changes

### ISSUE THREAD

**Issue by seandilda** [sclorg/rails-ex#114]
Can you provide a summary of changes from a standard rails app?

While this example is useful for seeing how a rails app might work in openshift, it doesn't list all the changes that are needed for a standard rails app to work with the openshift template.

For me this has become problematic as converting my existing rails applications has become trial and error as I run into errors, then look to see how it was solved.  This would have been easier if I had an initial list of things to change before I tried my app in openshift.   Along the same lines, I have no way to know if there are problems I'm experiencing (but not noticing yet) that are already solved in this example.

**Comment by pvalena** [comment]
This is rails app upgraded over time. Feel free to create a diff yourself!

Something like:
```
RAILS_ARGS= # please set it yourself
git clone https://github.com/sclorg/rails-ex/
mkdir test && cd test
rails new rails-app $ARGS
git init
git add -A .
git commit -am test-new
rm -rf rails-app
cp -r ../rails-ex rails-app
git add -A .
git commit -am rails-ex-app
git show
```
