### ISSUE TITLE
Support Ruby 2.7

### ISSUE THREAD

**Issue by pvalena** [sclorg/rails-ex#129]
> I get the following with 2.7:

@yselkowitz what command did you run, `s2i build`? Thanks for checking.

> /opt/rh/rh-ruby27/root/usr/share/rubygems/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /opt/app-root/src/Gemfile.lock. (Gem::GemNotFoundException)

Yes, this is caused by Ruby 2.7 switching to Bundler 2. Now it requires Gemfile.lock 'conversion'. Bundler 2 didn't bring any backward incompatible changes, but they may diverge further on, so they're not interchangable and thus require conversion.
https://bundler.io/blog/2019/01/03/announcing-bundler-2.html

IOW you can't have same Gemfile.lock for Ruby 2.7 and previous, unless we'll add `bundle update --bundler
` for it's `assemble`, like it's advised.

_Originally posted by @pvalena in https://github.com/sclorg/rails-ex/pull/128#issuecomment-661777969_

**Comment by pvalena** [comment]
The ultimate solution would be to detect this "old Gemfile.lock" and update to new bundler using advised command. That can be either done with custom `assemble` scriplet (prepending the container one) or in the container's assemble script itself.

@hhorak @voxik WDYT? Should we `bundle update --bundler` in assemble on behalf of users app by default?

_ _ _ _

_Note: there're two places (= assemble scripts) to solve this:_

 1. in [s2i-ruby-container ](https://github.com/sclorg/s2i-ruby-container/blob/master/2.7/s2i/bin/assemble) - the advantage being it's targeted for Ruby 2.7 solely
 2. in custom `assemble` script added to this app

**Comment by yselkowitz** [comment]
FWIW doing this in s2i-ruby-container makes sense to me.

**Comment by hhorak** [comment]
> @hhorak @voxik WDYT? Should we `bundle update --bundler` in assemble on behalf of users app by default?

I think Python container does something similar with `pip` as well, but **not by default**, only when `UPGRADE_PIP_TO_LATEST` is set (see https://github.com/sclorg/s2i-python-container/tree/master/3.8). I think updating it by default would be similar to the case we ship the upstream version, which is IMHO wrong from more reasons -- we nor users cannot control the version, upstream one can be broken, or changed too often... So, I'd personally prefer some bundler-alternative to `UPGRADE_PIP_TO_LATEST`.

**Comment by yselkowitz** [comment]
Correct me if I'm wrong, but there seems to be a difference.  `UPGRADE_PIP_TO_LATEST` actually updates pip, which is already present in the container.  OTOH AFAICS `bundle update --bundler` installs the gems specified in the Gemfile.lock and then updates `BUNDLED WITH` in the Gemfile.lock to the new version.  Even when I locally reverted #128 and ran `bundle update --bundler`, the only difference to the Gemfile.lock was `BUNDLED WITH`.

Furthermore, there is a fundamental difference between Python and Ruby (gems), in that the latter supports multiple parallel installed versions, so the versions that ship with the gem will still be present.  FWIW, in the case of rails-ex pre #128, only `rake` ended up with different versions than it started with, and the added version (which was actually older) did not clobber the preexisting version.

**Comment by voxik** [comment]
Wouldn't it be easier to just delete the Gemfile.lock and problem solved?

**Comment by voxik** [comment]
> Wouldn't it be easier to just delete the Gemfile.lock and problem solved?

I mean delete from the repository. Its value is dubious for simple example app without any nonstandard dependencies.

**Comment by voxik** [comment]
Or is it question for any generic Ruby/Rails app? Then probably the env variable could make a sense.

**Comment by hhorak** [comment]
> Wouldn't it be easier to just delete the Gemfile.lock and problem solved?

I think the reason for existence of this file is that the upstream projects were faulty sometimes and the Gemfile.lock was supposed to make sure the example application works the same always and OpenShift users don't see errors caused by changes in the upstream gem files. Maybe there is a middle way -- to specify version more exactly, but not using Gemfile.lock?

**Comment by voxik** [comment]
> Or is it question for any generic Ruby/Rails app? Then probably the env variable could make a sense.

But then this is wrong place for this ticket and it should be discussed at https://github.com/sclorg/s2i-ruby-container/

**Comment by voxik** [comment]
Also, if the `BUNDLED WITH\n   1.16.4` is dropped altogether, it will IMHO work independently of Bundler version.

**Comment by pvalena** [comment]
> Wouldn't it be easier to just delete the Gemfile.lock and problem solved?

If we don't lock it CI tests may run into problems on upstream updates. That's why we have `Gemfile.lock`, to have reproducible results.

**Comment by pvalena** [comment]
@voxik or do you mean just the `BUNDLED` part... didn't think of that.

**Comment by voxik** [comment]
> > Wouldn't it be easier to just delete the Gemfile.lock and problem solved?
> 
> If we don't lock it CI tests may run into problems on upstream updates. That's why we have `Gemfile.lock`, to have reproducible results.

At least we would move forward with the dependencies ....



> @voxik or do you mean just the `BUNDLED` part... didn't think of that.

Yes, I tested the removal with Bundler 2.1.4 and it worked unless I made some mistake.
