### ISSUE TITLE
Rails example issues

### ISSUE THREAD

**Issue by mfojtik** [sclorg/rails-ex#13]
Few more issues I found:

1) The `http_basic_authenticate_with name: "openshift", password: "secret", except: [:index, :show]` in the "articles" controller must use ENV["ADMIN_USER"]/ENV["ADMIN_PASSWORD"]. Also these are **not** set as env vars, but they just exists as parameters now

2) Navigate to `/articles/new` and get this error (the database exists at this point):

```
I, [2015-06-16T16:38:50.524034 #1]  INFO -- : Started GET "/articles/new" for 172.17.0.4 at 2015-06-16 16:38:50 +0000
I, [2015-06-16T16:38:50.526076 #1]  INFO -- : Processing by ArticlesController#new as HTML
E, [2015-06-16T16:38:50.529902 #1] ERROR -- : PG::UndefinedTable: ERROR:  relation "articles" does not exist
LINE 5:                WHERE a.attrelid = '"articles"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"articles"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

I, [2015-06-16T16:38:50.530846 #1]  INFO -- : Completed 500 Internal Server Error in 5ms (ActiveRecord: 2.1ms)
F, [2015-06-16T16:38:50.534080 #1] FATAL -- : 
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "articles" does not exist
LINE 5:                WHERE a.attrelid = '"articles"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"articles"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
  app/controllers/articles_controller.rb:20:in `new'
```

3) We have to store sessions into database (there is a configuration settings to do that)

**Comment by mfojtik** [comment]
@ewolinetz @bparees

**Comment by mfojtik** [comment]
3) is handled by sticky sessions at router, so ignore it :)

**Comment by bparees** [comment]
@mfojtik to be clear the default behavior is clientip based routing, but same difference basically.

**Comment by ewolinetz** [comment]
@mfojtik with 1) we are using admin user and admin password for the db connection currently... do we want to reuse those variables for that or create some new ones?

**Comment by mfojtik** [comment]
@ewolinetz afaik we use ADMIN_USER just in template:

``` console
π ~/go/src/github.com/openshift/rails-ex ack 'ADMIN_USER'
openshift/templates/rails-postgresql.json
334:      "name": "ADMIN_USERNAME",
```

We should use it for the app instead of 'openshift' and 'secret'.

**Comment by ewolinetz** [comment]
@mfojtik strange... it looks like that should have been removed.  that was remnants of the expression used in the config/database.yaml  It has since been replaced with POSTGRESQL_ADMIN_PASSWORD.  I would propose that they are instead renamed to something like APPLICATION_USER and APPLICATION_PASSWORD in addition to being added to the container's env.  Thoughts?

**Comment by mfojtik** [comment]
@ewolinetz +1 APPLICATION_USER sounds better... also make it clear that you will have to enter these in order to login to application :-) we should also set them to static values and document it.

**Comment by mfojtik** [comment]
@ewolinetz good news... 2) is not an issue... i scaled rails to 2 replicas and somehow screw the DB.

**Comment by ewolinetz** [comment]
@mfojtik hmm, i remember seeing another issue when scaling the app up with it interacting with the db but that's different than what you have pasted above...  strange

**Comment by ewolinetz** [comment]
@mfojtik i think i just came across 2) when testing my PR, it seems that it didn't run db migrate initially...? i'll test your PR and then try to recreate it again after

**Comment by bparees** [comment]
@ewolinetz I merged @mfojtik 's PR which does migration on deploy now.  so 2 should be fixed.

**Comment by bparees** [comment]
definitely needs more doc/cleanup around what user to use with the app though.

**Comment by mfojtik** [comment]
@bparees @ewolinetz i think we fixed all issues... I will do some more testing for rails-ex today, but closing this issue.
