### ISSUE TITLE
Update to Ruby on Rails 5.X

### ISSUE THREAD

**Issue by luciddreamz** [sclorg/rails-ex#65]
The current example is setup to [install the Rails 4.2.1 gem](https://github.com/openshift/rails-ex/blob/master/Gemfile#L6), but [Rails 5.0.0.1 is now available](http://weblog.rubyonrails.org/2016/8/11/Rails-5-0-0-1-4-2-7-2-and-3-2-22-3-have-been-released/). We should update this example to work with Rails 5.X.

**Comment by coreydaley** [comment]
Opened pull request #66

**Comment by coreydaley** [comment]
Closed via #66
