### ISSUE TITLE
build failed with ruby-20-rhel7 s2i builder image

### ISSUE THREAD

**Issue by wanghaoran1988** [sclorg/rails-ex#69]
ruby-20-rhel7 also failed with rails-ex now:
oc logs rails-ex-1-build                                                                                                                                                       rbenv:2.2.3 
Cloning "https://github.com/openshift/rails-ex" ...
        Commit: 26b5a51a3e97eb34fad01f7d602521b398a79bba (Merge pull request #68 from coreydaley/master)
        Author: Ben Parees <bparees@users.noreply.github.com>
        Date:   Wed Nov 9 12:23:27 2016 -0500

---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --deployment' ...
`x64_mingw` is not a valid platform. The available options are: [:ruby,
:ruby_18, :ruby_19, :ruby_20, :mri, :mri_18, :mri_19, :mri_20, :rbx, :jruby,
:mswin, :mingw, :mingw_18, :mingw_19, :mingw_20]
error: build error: non-zero (13) exit code from registry.ops.openshift.com/openshift3/ruby-20-rhel7@sha256:080d6a3b7cc7d221b2d5cd1fa25c48c844a51fae7474884a20c5627c3b8d7f13

**Comment by bparees** [comment]
Since we moved the rails-ex to rails5, it probably can't be built by ruby2.0 anymore.  @coreydaley if there's a quick fix we can do to the sample, let's do it, but otherwise i'm ok with closing this as "won't fix" and making sure none of our documented tutorials/examples suggest using this repo with ruby2.0.

**Comment by coreydaley** [comment]
According to the official documentation, Rails 5 requires ruby 2.2.2 or newer.
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions
