### ISSUE TITLE
Document how to change for additional steps

### ISSUE THREAD

**Issue by chargio** [sclorg/rails-ex#86]
It is possible to perform additional steps (i.e. update bundler)?

**Comment by chargio** [comment]
I've create more .s2i/save-artifacts and .s2i/assemble (with execution rights). But nothing happens

**Comment by chargio** [comment]
It was in .s2i/bin/assemble, now I've got passed that moment.
Executing 

gem install bundler -f
npm install yarn
node_modules/yarn/bin/yarn install

**Comment by chargio** [comment]
The build got stuck with yarn ...:(
Modifying it for bower (deprecated, by the way)

**Comment by chargio** [comment]
My .s2i/bin/assemble file installs the latest bundler, bower, and install javascript:

```bash
#!/bin/bash
echo "Updating bundler to new version"
cd $HOME
gem install bundler -f
echo "moving bundler to /tmp/src"
cp -r ./bin /tmp/src
rm -rf ./bin/

echo "Executing original script:"
/usr/libexec/s2i/assemble
rc=$?

if [ $rc -eq 0 ]; then
    echo "After successful assembling"
    npm install bower
    node_modules/bower/bin/bower install
    echo "Finished install bower assets"
else
    echo "After failed assembling"
fi

exit $rc

**Comment by coreydaley** [comment]
Documentation for how to perform additional instructions are located in the docs folder of this repository here:   https://github.com/openshift/source-to-image/tree/master/docs

information specific to the assemble script is located in this user guide: https://github.com/openshift/source-to-image/blob/master/docs/user_guide.md
