### ISSUE TITLE
rails-ex repo does not support ruby version below 2.3

### ISSUE THREAD

**Issue by xiuwang** [sclorg/rails-ex#92]
@bparees When I do s2i using ruby-2.2-rhel7 with rails-ex repo, I got this error.

Cloning "https://github.com/openshift/rails-ex" ... Commit: 099b107f67f7df550b16863272708a7f7d59ba9 (Merge pull request #91 from snumano/master) Author: Ben Parees <bparees@users.noreply.github.com> Date: Tue Jul 25 11:28:44 2017 -0400 ---> Installing application source ... ---> Building your Ruby application from source ... ---> Running 'bundle install --deployment --without development:test' ... 
Fetching gem metadata from https://rubygems.org/.......... 
Fetching additional metadata from https://rubygems.org/.. 
Installing rake 12.0.0 
Installing concurrent-ruby 1.0.5 
Installing i18n 0.8.4 
Installing minitest 5.10.2 
Installing thread_safe 0.3.6 
Installing tzinfo 1.2.3
Installing activesupport 5.1.2 
Installing builder 3.2.3 
Installing erubi 1.6.0 
Installing mini_portile2 2.2.0 
Installing nokogiri 1.8.0 
Installing rails-dom-testing 2.0.3 
Installing loofah 2.0.3 
Installing rails-html-sanitizer 1.0.3 
Installing actionview 5.1.2 
Installing rack 2.0.3 
Installing rack-test 0.6.3 
Installing actionpack 5.1.2
 Installing nio4r 2.1.0 
Installing websocket-extensions 0.1.2 
Installing websocket-driver 0.6.5 
Installing actioncable 5.1.2 
Installing globalid 0.4.0 
Installing activejob 5.1.2 
Installing mime-types-data 3.2016.0521 
Installing mime-types 3.1
 Installing mail 2.6.6 
Installing actionmailer 5.1.2 
Installing activemodel 5.1.2 
Installing arel 8.0.0 
Installing activerecord 5.1.2 
Installing coffee-script-source 1.12.2 
Installing execjs 2.7.0 
Installing coffee-script 2.4.1
Installing method_source 0.8.2 
Installing thor 0.19.4 
Installing railties 5.1.2 
Installing coffee-rails 4.2.2 
Installing ffi 1.9.18 
Installing multi_json 1.12.1 
Installing jbuilder 2.7.0 
Installing rb-fsevent 0.9.8 
Installing rb-inotify 0.9.10 
Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2. An error occurred while installing ruby_dep (1.5.0), and Bundler cannot continue. 
Make sure that `gem install ruby_dep -v '1.5.0'` succeeds before bundling. error: build error: non-zero (13) exit code from brew-***/rhscl/ruby-22-rhel7@sha256:01d956b46d17bd60650dabc0cfb925a4d1c688bb3473357f30cfa8bda3f676ae

**Comment by xiuwang** [comment]
Does the rails-ex repo not support ruby version below 2.3, I don't see any word in Readme

**Comment by coreydaley** [comment]
@xiuwang Can you please provide the command you are running to produce the above results?

**Comment by xiuwang** [comment]
@coreydaley you can reproduce this as below cmd:
step1.: $oc new-app ruby:2.2 https://github.com/openshift/rails-ex
step2:  After build failed,check build logs.
           $ oc logs -f rails-ex-1

**Comment by coreydaley** [comment]
@xiuwang I am unable to duplicate this issue.
Can you please provide the results of the following commands?
oc version
uname -a

**Comment by xiuwang** [comment]
$oc get builds  -n xiu1
NAME         TYPE      FROM          STATUS                    STARTED         DURATION
rails-ex-1   Source    Git@9099b10   Failed (AssembleFailed)   4 minutes ago   1m33s
 
$oc version
oc v3.6.173.0.2
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://host-****-.host.centralci.eng.rdu2.redhat.com:8443
openshift v3.6.173.0.2
kubernetes v1.6.1+5115d708d7
[root@host ~]# uname -a
Linux host-**-.host.centralci.eng.rdu2.redhat.com 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
