### ISSUE TITLE
Can't send emails from my openshift v3 app

### ISSUE THREAD

**Issue by marcosmartingm** [sclorg/rails-ex#98]
I dont know where ask it. 
When my app in openshift v3 send one email (using server: smtp.gmail.com, port: 587... etc), it respond with 500 and: SocketError (getaddrinfo: Servname not supported for ai_socktype)
Whats appening? what can i do to solve this problem?

**Comment by coreydaley** [comment]
Unfortunately this is not the correct place for this question, however, here are a couple of places that would be appropriate:

https://stackoverflow.com/questions/tagged/openshift
https://help.openshift.com/forms/community-contact.html
